Repository githubschool/road-trip, pull requests merged in 2020-06, with the labels that each got.

#15 Caption change
  _slides/17-mwaes6.md
Labels: caption-updates

#30 Update caption for Robocat
  _slides/20-ruleclouds.md
Labels: caption-updates

#29 Jliudmv caption
  _slides/13-jliudmv.md
Labels: caption-update

#22 Edit caption by me, Jawad
  _slides/11-jawadferouz.md
Labels: caption updates

#24 Added zipcode
  _slides/15-khanhbtran.md
Labels: caption-update

#12 Update caption to be more descriptive
  _slides/02-ericalloyd.md
Labels: caption-updates

#19 Edit caption to match graphic
  _slides/12-jeffreyfollis.md
Labels: caption-update

#20 Update caption for description
  _slides/08-csandhu.md
Labels: caption-updates- csandhu

#28 edit caption for description
  _slides/22-wadeDMV.md
Labels: caption-updates

#17 Update caption to be more descriptive
  _slides/24-mwatd1.md
Labels: Caption-updated

#21 Edit caption to add location
  _slides/10-gchow-dmv.md
Labels: caption-update

#14 Pulling kanasanjeevan-caption Branch
  _slides/14-kanasanjeevan.md
Labels: good first issue
